# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"device": "00_core.ipynb",
         "to_rgb": "01_cellular_automata.ipynb",
         "apply_dbscan_to_mask": "00_core.ipynb",
         "grid_search_DBSCAN_params": "00_core.ipynb",
         "label_mask_and_add_to_clusters": "00_core.ipynb",
         "merge_labeled_clusters": "00_core.ipynb",
         "get_min_max": "00_core.ipynb",
         "pad_two_size_multiple_32": "00_core.ipynb",
         "correct_label_in_plot": "01_cellular_automata.ipynb",
         "get_big_lesions_labels": "00_core.ipynb",
         "read_covid_CT_and_mask": "00_core.ipynb",
         "normalize_rotate": "00_core.ipynb",
         "normalizePatches": "00_core.ipynb",
         "plot_3d_2": "00_core.ipynb",
         "len_multiple_32": "00_core.ipynb",
         "select_lesions_match_conditions": "00_core.ipynb",
         "make_list_of_targets_and_seeds": "00_core.ipynb",
         "create_sobel_and_identity": "01_cellular_automata.ipynb",
         "ca_model_perception": "01_cellular_automata.ipynb",
         "plot_loss_and_lesion_synthesis": "01_cellular_automata.ipynb"}

modules = ["core.py",
           "cellular_automata.py"]

doc_url = "https://octaviomtz.github.io/c19_synthesis/"

git_url = "https://github.com/octaviomtz/c19_synthesis/tree/{branch}/"

def custom_doc_links(name): return None
