# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"to_rgb": "00_core.ipynb",
         "apply_dbscan_to_mask": "00_core.ipynb",
         "grid_search_DBSCAN_params": "00_core.ipynb",
         "label_mask_and_add_to_clusters": "00_core.ipynb",
         "merge_labeled_clusters": "00_core.ipynb",
         "get_min_max": "00_core.ipynb",
         "pad_two_size_multiple_32": "00_core.ipynb",
         "correct_label_in_plot": "00_core.ipynb",
         "get_big_lesions_labels": "00_core.ipynb",
         "read_covid_CT_and_mask": "00_core.ipynb",
         "normalize_rotate": "00_core.ipynb",
         "normalizePatches": "00_core.ipynb",
         "plot_3d_2": "00_core.ipynb",
         "filename": "00_core.ipynb",
         "path_source": "00_core.ipynb",
         "path_dest": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://octaviomtz.github.io/c19_synthesis/"

git_url = "https://github.com/octaviomtz/c19_synthesis/tree/{branch}/"

def custom_doc_links(name): return None
